name: mci_flutter_lib
description: A starting point for Dart libraries or applications.
version: 1.4.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.0
  collection: ^1.16.0
  cross_file: ^0.3.3
  crypto: ^3.0.1
  equatable: ^2.0.0
  firebase_analytics: ^9.1.7
  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
  firebase_messaging: ^11.3.0
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^9.5.2
  fluttertoast: ^8.0.9
  geo: ^0.3.0
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  intl: ^0.17.0-nullsafety.2
  maps_toolkit: ^2.0.0
  permission_handler: ^9.2.0
  photo_view: ^0.12.0
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.3
  shimmer: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.1

# Use to generate translations to create CurrentLocalisationDelegate
flutter:
  generate: true
