name: mci_flutter_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  google_maps_flutter: ^2.1.0
  geo: ^0.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
